# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }
index:
    path: /Form
    defaults: { _controller: 'App\Controller\FormController::numberAction' }
From2:
    path: /Form2
    defaults: { _controller: 'App\Controller\FormInvoiceController::from_actionInvoice' }

